name: 'Try Runtime'
description: 'Runs try-runtime on-runtime-upgrade on the specified chain and runtime'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  snap:
    description: 'Path to a previously taken snapshot'
    default: '/tmp/default.snap'
  runtime:
    description: 'Path to a try-runtime enabled runtime to test migrations for'
    required: true
  checks:
    description: 'Checks to run'
    default: 'all'
  options:
    description: 'try-runtime command line options'
    default: ''
    required: false
runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - ${{ inputs.snap }}
    - ${{ inputs.runtime }}
    - ${{ inputs.checks }}
    - ${{ inputs.options }}
