name: 'Try Runtime - create snapshot'
description: 'Runs try-runtime to create a snapshot'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  url:
    description: 'URL of the node to take a snapshot from'
    required: true
  snap:
    description: 'Path to a previously taken snapshot, if does not exists we will create it'
    default: '/tmp/default.snap'
  options:
    description: "Other command line options"
    required: false
 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.snap }}
    - ${{ inputs.options }}